plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rksolution.urdusikhe'
    compileSdk 35

    defaultConfig {
        applicationId 'com.rksolution.urdusikhe'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:25.4.0'
}
